services:
  - type: web
    name: lilypad-erp-dev
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: "npm install --legacy-peer-deps"
    startCommand: "node app.js"
    healthCheckPath: "/api/v1/lilypad/tickets/todo"
    autoDeploy: true
    disk:
      name: lilypad-uploads
      mountPath: /var/data/uploads
      sizeGB: 5
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 16.20.2
      - key: PORT
        value: 8118
      - key: PRIMARY_INBOUND_EMAIL
        value: support@lilypad.local
      - key: ENABLE_ANTI_SPAM_SHIELD
        value: "true"
      - key: SESSION_SECRET
        sync: false

